# fly.toml app configuration file generated for ollama-frontend on 2025-01-25T14:00:40+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ollama-frontend'
primary_region = 'lhr'

[build]

[[mounts]]
  source = 'data'
  destination = '/app/backend/data'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
